### ISSUE TITLE
Возможно ли использовать эту библиотеку для HL2DEMO ?

### ISSUE THREAD

**Issue by T1MOXA** [VitalyArt/hltv-demo-parser#4]
Я не нашел информации о отличиях структуры, разве что у вас заголовок прописан HLDEMO, а не HL2DEMO

**Comment by VitalyArt** [comment]
На сколько я помню в движве source похожая структура демо файлов. Можно попробовать заменить HLDEMO, на HL2DEMO и посмотреть что будет. Постараюсь на днях глянуть

**Comment by T1MOXA** [comment]
Я пробовал так сделать, вишло не очень, но  я уже не помню что именно пошло не так...

**Comment by VitalyArt** [comment]
Вот что смог найти. Там есть пример парсинга демо файла на PHP.
https://developer.valvesoftware.com/wiki/DEM_Format
