### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by antimYT** [VitalyArt/hltv-demo-parser#5]
После строки `$parser = new \VitalyArt\DemoParser();` перестает выполняться любой код. 
Никаких ошибок и исключений не вылетает.

**Comment by VitalyArt** [comment]
У меня было ошибка в описании, сейчас исправил.
Попробуй так:

```
$parser = new \VitalyArt\DemoParser\Parser();
$parser->setDemoFile('/path/to/demo/pub-1609152130-de_dust2_2x2.dem');
```

А вот по поводу того, что не выводятся ошибки, тут надо смотреть настройки сервера.

**Comment by VitalyArt** [comment]
Прошло 14 дней, закрываю этот вопрос.
Если будут проблемы, открой новый issue
