### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by MichaelKheel** [VitalyArt/hltv-demo-parser#6]
Attempted to load class "DemoParser" from namespace "VitalyArt".
Did you forget a "use" statement for another namespace?

Подключен композером, скрипт не работает.
Пытался разными способами, мой обработчик ошибок, выдал это. Если подключать напрямую, пишет, что \VitalyArt\DemoParser Class not found.

**Comment by VitalyArt** [comment]
У меня было ошибка в описании, сейчас исправил.
Попробуй так:
`
$parser = new \VitalyArt\DemoParser\Parser();
$parser->setDemoFile('/path/to/demo/pub-1609152130-de_dust2_2x2.dem');
`
