### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by kingsh2012** [VitalyArt/hltv-demo-parser#7]
Hello, can I use this software for cstrike1.6? 
How to parse pov demo or hltv demo and convert it into video output?

**Comment by VitalyArt** [comment]
Hello.
This package is for parsing metadata from a demo files based on GoldSrc engine (Half-Life 1, Counter-String 1.6, etc...).
Sorry, but you will not be able to use this package to get a video

**Comment by kingsh2012** [comment]
thx
